from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import PureWindowsPath
from typing import List, Optional

from neos.secrets import generate


class RecordType(Enum):
    OBJECT = "object"
    LINK = "link"
    DIRECTORY = "directory"


@dataclass
class NeosRecord:
    id: str
    globalVersion: int
    localVersion: int
    lastModifyingUserId: str
    name: str
    recordType: RecordType
    path: str
    isPublic: bool
    isForPatrons: bool
    isListed: bool
    isDeleted: bool
    lastModificationTime: datetime
    visits: int
    rating: int
    ownerId: str


class NeosLink(NeosRecord):
    assetUri: str


class NeosDirectory(NeosRecord):
    lastModifyingMachineId: str
    ownerName: str
    tags: List[str] = field(default_factory=list)
    creationTime: datetime

    @property
    def content_path(self) -> str:
        return str(PureWindowsPath(self.path, self.name))


class NeosObject(NeosRecord):
    assetUri: str
    lastModifyingMachineId: str
    ownerName: str
    tags: List[str] = field(default_factory=list)
    creationTime: datetime


typeMapping = {
    RecordType.DIRECTORY: NeosDirectory,
    RecordType.LINK: NeosLink,
    RecordType.OBJECT: NeosObject,
}


@dataclass
class LoginDetails:
    """
    the login details for neos. SecretMachineId can be generated by neos.secrets
    """

    Email: str
    Password: str
    SecretMachineId: str = field(default_factory=generate)


@dataclass
class ProfileData:
    iconUrl: Optional[str]
    tokenOutOut: Optional[List[str]] = field(default_factory=list)


@dataclass
class CreditData:
    KFC: float
    NCR: float
    CDFT: float


@dataclass
class PatreonData:
    isPatreonSupporter: bool
    patreonId: Optional[str]
    lastPatreonPledgeCents: int
    lastTotalCents: int
    lastTotalUnits: int
    minimumTotalUnits: int
    externalCents: int
    lastExternalCents: int
    hasSupported: bool
    lastIsAnorak: bool
    priorityIssue: int
    lastPlusActivationTime: datetime
    lastActivationTime: datetime
    lastPlusPledgeAmount: int
    lastPaidPledgeAmount: int
    accountName: str
    currentAccountType: int
    currentAccountCents: int
    pledgedAccountType: int


@dataclass
class NeosUser:
    id: str
    username: str
    normalizedUsername: str
    email: Optional[str]
    registrationDate: datetime
    isVerified: bool
    quotaBytes: Optional[int]
    isLocked: bool
    accountBanExpiration: Optional[datetime]
    publicBanExpiration: Optional[datetime]
    spectatorBanExpiration: Optional[datetime]
    muteBanExpiration: Optional[datetime]
    usedBytes: Optional[int]
    profile: Optional[ProfileData]
    credits: Optional[CreditData]
    NCRdepositAddress: Optional[str]
    patreonData: Optional[PatreonData]
    tags: Optional[List[str]] = field(default_factory=list)


